### ISSUE TITLE
Falta de link de navegação entre as páginas

### ISSUE THREAD

**Issue by paulocuambe** [IUX7K/ui4noobs#3]
Para melhorar a experiência do leitor as páginas deviam apontar umas para as outras para evitar o processo massante de voltar sempre ao directório raiz e procurar a página seguinte.

Eu posso trabalhar nisso se você quiser e até quarta-feira mando um pull request.

**Comment by setekpro** [comment]
Olá Paulo, tudo bem?

Obrigado pela sua sugestão e pela sua disponibilidade por tornar esse repositório melhor, aguardo sua contribuição! 

Atenciosamente, 7K.

**Comment by paulocuambe** [comment]
@IUX7K eu achei que fosse levar muito tempo, acabei terminando mais rápido que o esperado. Aqui está o PR #4
